esphome:
  name: wemos18650
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_pwd

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd

captive_portal:

sensor:
  - platform: dht
    pin: D1
    temperature:
      name: "wemos18650.temperature"
    humidity:
      name: "wemos18650.humidity"
    update_interval: 60s