esphome:
  name: max6675-temp-sensor

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_pwd

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd

spi:
  clk_pin: D5
  miso_pin: D7

sensor:
  - platform: max6675
    name: "Ooni Temperature"
    cs_pin: D2
    update_interval: 20s